server:
  port: 8080
spring:
  thymeleaf:
    check-template: true
  application:
    name: CorporatePortalApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/corporate-portal
    username: postgres
    password: egaroot
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
