server:
  port: 8080
spring:
  thymeleaf:
    check-template: true
  application:
    name: CorporatePortalApplication
  datasource:
    url: jdbc:h2:mem:cor-portal-db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
